In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('F:\Python\Deep-Learning-and-Computer-vision\Dataset\DailyDelhiClimateTrain.csv')

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\VIKASH KUMAR\AppData\Local\Temp\ipykernel_41240\3339585257.py:1: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv('F:\Python\Deep-Learning-and-Computer-vision\Dataset\DailyDelhiClimateTrain.csv')

In [3]:
df.head()

         date   meantemp   humidity  wind_speed  meanpressure
0  2013-01-01  10.000000  84.500000    0.000000   1015.666667
1  2013-01-02   7.400000  92.000000    2.980000   1017.800000
2  2013-01-03   7.166667  87.000000    4.633333   1018.666667
3  2013-01-04   8.666667  71.333333    1.233333   1017.166667
4  2013-01-05   6.000000  86.833333    3.700000   1016.500000

In [6]:
df = df[['date', 'meantemp']]

In [7]:
df.head()

         date   meantemp
0  2013-01-01  10.000000
1  2013-01-02   7.400000
2  2013-01-03   7.166667
3  2013-01-04   8.666667
4  2013-01-05   6.000000